agent:
  name: "ReactDocsAgent"
  description: "An agent designed to process and interact with documentation files in the ai/agents/react/docs directory."

tasks:
  - name: "Analyze Documentation"
    description: "Read and analyze the documentation files to extract key information."
    steps:
      - name: "Read Files"
        command: "cat ai/agents/react/docs/*.md"
        description: "Read all markdown files in the docs directory."

      - name: "Extract Information"
        command: "python extract_info.py"
        description: "Run a script to extract key information from the documentation."

notifications:
  on_failure: "Send email notification to admin@domain.com"
  on_success: "Log success message and update status dashboard"
